// Copyright (c) Jared Taylor

#pragma once

#include "NativeGameplayTags.h"

namespace FDoorTags
{
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_CanDoorChangeToAnyState);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_OnCooldown);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_InMotion);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_ClientDoorSide);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_CanChangeDoorState);
	
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_DoorNotValid);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_Locked);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_AlreadyClosed);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_AlreadyOpen);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_NoAccessFromFront);
	DOORS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door_Fail_NoAccessFromBack);
}